apiVersion: v1
kind: Pod

metadata:
  name: fortune-pod
  labels:
    name: fortune-pod
    version: "v1"
    owner: danialchanee
spec:
  containers:
    - name: fortune
      image: danialchanee/fortune
      imagePullPolicy: Always
      env:
      - name: APP_PORT
        value: "3000"
      ports:
      - name: fortune-port
        containerPort: 3000
